"use client";

import { useMemo, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  AlarmClock,
  AlertTriangle,
  CalendarClock,
  Check,
  CheckCircle2,
  ClipboardList,
  Clock,
  ListChecks,
  Loader2,
  MoreHorizontal,
  Pause,
  Plus,
  RotateCcw,
  Send,
  Sparkles,
  Trash2,
  X,
} from "lucide-react";
import type {
  AdminTaskCategory,
  AdminTaskPriority,
  AdminTaskStatus,
  ProfileStatus,
  TransactionStatus,
} from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { formatDateTime, formatUSD } from "@/lib/utils";
import {
  adminAutoDetectTasks,
  adminCreateTask,
  adminDeleteTasks,
  adminReopenTask,
  adminResolveTask,
  adminSnoozeTask,
} from "../actions";

type TaskRow = {
  id: string;
  title: string;
  category: AdminTaskCategory;
  status: AdminTaskStatus;
  priority: AdminTaskPriority;
  customerId: string | null;
  profileId: string | null;
  transactionId: string | null;
  customerEmail: string | null;
  customerBlocked: boolean | null;
  customerTelegramId: string | null;
  profileName: string | null;
  transactionRef: string | null;
  amountCents: number | null;
  paidAt: string | null;
  dueAt: string | null;
  snoozedUntil: string | null;
  reason: string | null;
  notes: string | null;
  autoGenerated: boolean;
  createdAt: string;
  resolvedAt: string | null;
  createdByLabel: string | null;
  resolvedByLabel: string | null;
};

type CustomerOption = {
  id: string;
  email: string;
  name: string | null;
  blocked: boolean;
};

type ProfileOption = {
  id: string;
  userId: string;
  label: string;
  status: ProfileStatus;
};

type TransactionOption = {
  id: string;
  reference: string;
  amountCents: number;
  senderName: string;
  status: TransactionStatus;
  createdAt: string;
  userId: string;
  profileId: string;
  userEmail: string;
  profileLabel: string;
};

const TABS = [
  { key: "OPEN", label: "Open" },
  { key: "OVERDUE", label: "Overdue" },
  { key: "SNOOZED", label: "Snoozed" },
  { key: "RESOLVED", label: "Resolved" },
  { key: "ALL", label: "All" },
] as const;

const CATEGORY_META: Record<
  AdminTaskCategory,
  { label: string; variant: "default" | "warning" | "destructive" | "outline" | "success" | "secondary" }
> = {
  PAYMENT_HOLD: { label: "Payment hold", variant: "warning" },
  PENDING_CONFIRMATION: { label: "Pending confirmation", variant: "warning" },
  RESTRICTED_ACCOUNT: { label: "Restricted account", variant: "destructive" },
  PROFILE_REVIEW: { label: "Profile review", variant: "default" },
  SCHEDULED_TRANSFER: { label: "Scheduled transfer", variant: "default" },
  REFUND_FOLLOWUP: { label: "Refund follow-up", variant: "secondary" },
  COMPLIANCE_REVIEW: { label: "Compliance review", variant: "outline" },
  OTHER: { label: "Other", variant: "outline" },
};

const PRIORITY_META: Record<
  AdminTaskPriority,
  { label: string; badgeClass: string; dotClass: string }
> = {
  LOW: {
    label: "Low",
    badgeClass:
      "bg-slate-50 text-slate-700 ring-slate-200 dark:bg-slate-800/60 dark:text-slate-300 dark:ring-slate-700",
    dotClass: "bg-slate-400 dark:bg-slate-500",
  },
  NORMAL: {
    label: "Normal",
    badgeClass:
      "bg-blue-50 text-blue-700 ring-blue-200 dark:bg-blue-950/40 dark:text-blue-300 dark:ring-blue-900",
    dotClass: "bg-blue-500 dark:bg-blue-400",
  },
  HIGH: {
    label: "High",
    badgeClass:
      "bg-amber-50 text-amber-800 ring-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:ring-amber-900",
    dotClass: "bg-amber-500 dark:bg-amber-400",
  },
  URGENT: {
    label: "Urgent",
    badgeClass:
      "bg-rose-50 text-rose-700 ring-rose-200 dark:bg-rose-950/40 dark:text-rose-300 dark:ring-rose-900",
    dotClass: "bg-rose-500 dark:bg-rose-400",
  },
};

/**
 * Small numeric chip shown inside category filter pills. Renders nothing when
 * the count is zero so empty categories stay visually quiet, but switches to a
 * higher-contrast style when the parent pill is selected.
 */
function CountBadge({ count, active }: { count: number; active: boolean }) {
  if (count <= 0) return null;
  return (
    <span
      className={`inline-flex min-w-[1.25rem] items-center justify-center rounded-full px-1.5 py-0.5 text-[10px] font-semibold tabular-nums leading-none ${
        active
          ? "bg-primary text-primary-foreground"
          : "bg-muted text-foreground"
      }`}
    >
      {count}
    </span>
  );
}

function buildTasksHref(
  status: (typeof TABS)[number]["key"],
  category: AdminTaskCategory | null,
) {
  const params = new URLSearchParams();
  if (status !== "OPEN") params.set("status", status);
  if (category) params.set("category", category);
  const qs = params.toString();
  return qs.length === 0 ? "/admin/tasks" : `/admin/tasks?${qs}`;
}

function buildCategoryHref(
  status: (typeof TABS)[number]["key"],
  category: AdminTaskCategory | null,
) {
  return buildTasksHref(status, category);
}

function TelegramHandleLink({ handle }: { handle: string }) {
  const trimmed = handle.trim().replace(/^@/, "");
  const isUsername = /^[A-Za-z0-9_]{5,32}$/.test(trimmed);
  if (isUsername) {
    return (
      <a
        href={`https://t.me/${trimmed}`}
        target="_blank"
        rel="noreferrer"
        className="inline-flex items-center gap-1 font-medium text-primary hover:underline"
      >
        <Send className="h-3 w-3" />@{trimmed}
      </a>
    );
  }
  return (
    <span className="inline-flex items-center gap-1 font-mono text-xs text-muted-foreground">
      <Send className="h-3 w-3" />
      {handle}
    </span>
  );
}

function StatusBadge({ status, dueAt }: { status: AdminTaskStatus; dueAt: string | null }) {
  if (status === "RESOLVED") {
    return (
      <Badge variant="success">
        <CheckCircle2 className="h-3 w-3" /> Resolved
      </Badge>
    );
  }
  if (status === "SNOOZED") {
    return (
      <Badge variant="outline">
        <Pause className="h-3 w-3" /> Snoozed
      </Badge>
    );
  }
  const overdue = dueAt && new Date(dueAt).getTime() < Date.now();
  return (
    <Badge variant={overdue ? "destructive" : "warning"}>
      {overdue ? (
        <>
          <AlertTriangle className="h-3 w-3" /> Overdue
        </>
      ) : (
        <>
          <Clock className="h-3 w-3" /> Open
        </>
      )}
    </Badge>
  );
}

export function TasksClient({
  tasks,
  customers,
  profiles,
  transactions,
  active,
  activeCategory,
  counts,
  categoryCounts,
}: {
  tasks: TaskRow[];
  customers: CustomerOption[];
  profiles: ProfileOption[];
  transactions: TransactionOption[];
  active: (typeof TABS)[number]["key"];
  activeCategory: AdminTaskCategory | null;
  counts: Record<(typeof TABS)[number]["key"], number>;
  categoryCounts: Record<AdminTaskCategory, number>;
}) {
  const router = useRouter();
  const [creating, setCreating] = useState(false);
  const [resolving, setResolving] = useState<TaskRow | null>(null);
  const [snoozing, setSnoozing] = useState<TaskRow | null>(null);
  const [viewing, setViewing] = useState<TaskRow | null>(null);
  const [resolutionNote, setResolutionNote] = useState("");
  const [snoozeUntil, setSnoozeUntil] = useState("");
  const [autoPending, startAutoTransition] = useTransition();
  const [actionPending, startActionTransition] = useTransition();
  const [selectionMode, setSelectionMode] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deletePending, startDeleteTransition] = useTransition();

  const allSelected =
    tasks.length > 0 && tasks.every((t) => selected.has(t.id));

  const toggleRow = (id: string) =>
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const toggleAll = () =>
    setSelected(allSelected ? new Set() : new Set(tasks.map((t) => t.id)));

  const exitSelection = () => {
    setSelectionMode(false);
    setSelected(new Set());
  };

  const runAutoDetect = () => {
    startAutoTransition(async () => {
      try {
        const res = await adminAutoDetectTasks();
        const parts: string[] = [];
        if (res.created > 0)
          parts.push(`${res.created} task${res.created === 1 ? "" : "s"} added`);
        if (res.woken > 0)
          parts.push(`${res.woken} snooze${res.woken === 1 ? "" : "s"} woken`);
        toast.success(parts.length > 0 ? parts.join(", ") : "Queue is up to date.");
        router.refresh();
      } catch (err) {
        toast.error(
          err instanceof Error ? err.message : "Auto-detect failed",
        );
      }
    });
  };

  const submitResolve = () => {
    if (!resolving) return;
    startActionTransition(async () => {
      const res = await adminResolveTask({
        id: resolving.id,
        resolutionNote: resolutionNote.trim() || undefined,
      });
      if (res.ok) {
        toast.success("Task resolved.");
        setResolving(null);
        setResolutionNote("");
        router.refresh();
      } else {
        toast.error(res.error);
      }
    });
  };

  const submitSnooze = () => {
    if (!snoozing) return;
    const parsed = new Date(snoozeUntil);
    if (Number.isNaN(parsed.getTime())) {
      toast.error("Pick a valid snooze date");
      return;
    }
    startActionTransition(async () => {
      const res = await adminSnoozeTask({ id: snoozing.id, snoozeUntil: parsed });
      if (res.ok) {
        toast.success("Task snoozed.");
        setSnoozing(null);
        setSnoozeUntil("");
        router.refresh();
      } else {
        toast.error(res.error);
      }
    });
  };

  const reopen = (id: string) => {
    startActionTransition(async () => {
      const res = await adminReopenTask(id);
      if (res.ok) {
        toast.success("Task reopened.");
        router.refresh();
      } else {
        toast.error(res.error);
      }
    });
  };

  const deleteSelected = () => {
    startDeleteTransition(async () => {
      const res = await adminDeleteTasks([...selected]);
      if (res.ok) {
        toast.success(
          `${res.deleted} task${res.deleted === 1 ? "" : "s"} deleted.`,
        );
        setConfirmDelete(false);
        exitSelection();
        router.refresh();
      } else {
        toast.error(res.error);
      }
    });
  };

  return (
    <>
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap gap-1 rounded-lg border bg-card p-1 text-sm">
          {TABS.map((t) => (
            <Link
              key={t.key}
              href={buildTasksHref(t.key, activeCategory)}
              className={`rounded-md px-4 py-2 text-center font-medium transition-colors ${
                active === t.key
                  ? "bg-primary/10 text-primary"
                  : "text-muted-foreground hover:bg-accent"
              }`}
            >
              {t.label}{" "}
              <span className="ml-1 text-xs opacity-70">({counts[t.key]})</span>
            </Link>
          ))}
        </div>
        <div className="flex items-center gap-2">
          {selectionMode ? (
            <>
              <span className="text-sm text-muted-foreground">
                {selected.size} selected
              </span>
              <Button
                variant="destructive"
                size="sm"
                disabled={selected.size === 0}
                onClick={() => setConfirmDelete(true)}
              >
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button variant="outline" size="sm" onClick={exitSelection}>
                <X className="h-4 w-4" /> Cancel
              </Button>
            </>
          ) : (
            <>
              {tasks.length > 0 && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSelectionMode(true)}
                >
                  <ListChecks className="h-4 w-4" /> Select
                </Button>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={runAutoDetect}
                disabled={autoPending}
              >
                {autoPending ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Sparkles className="h-4 w-4" />
                )}
                Auto-detect
              </Button>
              <Dialog open={creating} onOpenChange={setCreating}>
                <DialogTrigger asChild>
                  <Button>
                    <Plus /> New task
                  </Button>
                </DialogTrigger>
                {creating && (
                  <NewTaskDialog
                    customers={customers}
                    profiles={profiles}
                    transactions={transactions}
                    onDone={() => {
                      setCreating(false);
                      router.refresh();
                    }}
                  />
                )}
              </Dialog>
            </>
          )}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <span className="mr-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          Category
        </span>
        <Link
          href={buildCategoryHref(active, null)}
          className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
            activeCategory === null
              ? "border-primary/30 bg-primary/10 text-primary"
              : "border-border bg-card text-muted-foreground hover:bg-accent hover:text-foreground"
          }`}
        >
          All
          <CountBadge
            count={Object.values(categoryCounts).reduce((a, b) => a + b, 0)}
            active={activeCategory === null}
          />
        </Link>
        {(Object.keys(CATEGORY_META) as AdminTaskCategory[])
          // Hide categories with zero uncompleted tasks UNLESS one is currently
          // selected (so the active pill stays visible until you switch away).
          .filter(
            (k) => categoryCounts[k] > 0 || activeCategory === k,
          )
          .map((k) => {
            const meta = CATEGORY_META[k];
            const isActive = activeCategory === k;
            return (
              <Link
                key={k}
                href={buildCategoryHref(active, isActive ? null : k)}
                className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
                  isActive
                    ? "border-primary/30 bg-primary/10 text-primary"
                    : "border-border bg-card text-muted-foreground hover:bg-accent hover:text-foreground"
                }`}
              >
                {meta.label}
                <CountBadge count={categoryCounts[k] ?? 0} active={isActive} />
              </Link>
            );
          })}
      </div>

      <p className="rounded-lg border border-dashed bg-muted/30 p-3 text-xs text-muted-foreground">
        Tip: <strong>Auto-detect</strong> scans for blocked accounts, profiles
        pending &gt; 48h, pending payments &gt; 72h, scheduled transfers whose
        ETA passed, and old refunds — seeding tasks for each. It also wakes
        snoozed tasks whose timer has elapsed. Safe to re-run; duplicates are
        skipped.
      </p>

      <Card>
        <CardContent className="p-0">
          {tasks.length === 0 ? (
            <div className="flex flex-col items-center gap-3 px-6 py-16 text-center text-sm text-muted-foreground">
              <ClipboardList className="h-8 w-8 opacity-50" />
              No tasks in this state.
              {active === "OPEN" && (
                <span className="text-xs">
                  Use <strong>Auto-detect</strong> to surface payments and
                  accounts that need follow-up, or create a task manually.
                </span>
              )}
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  {selectionMode && (
                    <TableHead className="w-10">
                      <input
                        type="checkbox"
                        checked={allSelected}
                        onChange={toggleAll}
                        aria-label="Select all tasks"
                        className="h-4 w-4 cursor-pointer accent-primary"
                      />
                    </TableHead>
                  )}
                  <TableHead>Task</TableHead>
                  <TableHead>Customer / profile</TableHead>
                  <TableHead className="text-right">Amount</TableHead>
                  <TableHead>Paid</TableHead>
                  <TableHead>Due</TableHead>
                  <TableHead>Priority</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="w-12" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {tasks.map((t) => {
                  const meta = CATEGORY_META[t.category];
                  const overdue =
                    t.status === "OPEN" &&
                    t.dueAt &&
                    new Date(t.dueAt).getTime() < Date.now();
                  return (
                    <TableRow
                      key={t.id}
                      className="cursor-pointer"
                      onClick={() => !selectionMode && setViewing(t)}
                    >
                      {selectionMode && (
                        <TableCell
                          className="w-10"
                          onClick={(e) => e.stopPropagation()}
                        >
                          <input
                            type="checkbox"
                            checked={selected.has(t.id)}
                            onChange={() => toggleRow(t.id)}
                            aria-label="Select task"
                            className="h-4 w-4 cursor-pointer accent-primary"
                          />
                        </TableCell>
                      )}
                      <TableCell>
                        <div className="font-medium">{t.title}</div>
                        <div className="mt-1 flex flex-wrap items-center gap-2 text-xs">
                          <Badge variant={meta.variant}>{meta.label}</Badge>
                          {t.autoGenerated && (
                            <span className="inline-flex items-center gap-1 rounded-md bg-muted px-1.5 py-0.5 text-[10px] font-medium text-muted-foreground">
                              <Sparkles className="h-3 w-3" /> auto
                            </span>
                          )}
                          {t.customerBlocked && (
                            <span className="inline-flex items-center gap-1 rounded-md bg-destructive/10 px-1.5 py-0.5 text-[10px] font-medium text-destructive">
                              blocked
                            </span>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="text-sm">
                          {t.customerEmail ?? (
                            <span className="text-muted-foreground">—</span>
                          )}
                        </div>
                        {t.profileName && (
                          <div className="text-xs text-muted-foreground">
                            {t.profileName}
                          </div>
                        )}
                      </TableCell>
                      <TableCell className="text-right font-semibold">
                        {t.amountCents != null ? (
                          formatUSD(t.amountCents)
                        ) : (
                          <span className="font-normal text-muted-foreground">
                            —
                          </span>
                        )}
                      </TableCell>
                      <TableCell className="whitespace-nowrap text-xs text-muted-foreground">
                        {t.paidAt ? formatDateTime(t.paidAt) : "—"}
                      </TableCell>
                      <TableCell
                        className={`whitespace-nowrap text-xs ${overdue ? "font-semibold text-destructive" : "text-muted-foreground"}`}
                      >
                        {t.dueAt ? formatDateTime(t.dueAt) : "—"}
                      </TableCell>
                      <TableCell>
                        <span
                          className={`inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[11px] font-medium ring-1 ring-inset ${PRIORITY_META[t.priority].badgeClass}`}
                        >
                          <span
                            className={`h-1.5 w-1.5 rounded-full ${PRIORITY_META[t.priority].dotClass}`}
                          />
                          {PRIORITY_META[t.priority].label}
                        </span>
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={t.status} dueAt={t.dueAt} />
                      </TableCell>
                      <TableCell onClick={(e) => e.stopPropagation()}>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon">
                              <MoreHorizontal className="h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuLabel>Actions</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            {t.status !== "RESOLVED" && (
                              <>
                                <DropdownMenuItem
                                  onClick={() => {
                                    setResolving(t);
                                    setResolutionNote("");
                                  }}
                                >
                                  <Check className="h-4 w-4 text-success" />
                                  Mark resolved
                                </DropdownMenuItem>
                                <DropdownMenuItem
                                  onClick={() => {
                                    setSnoozing(t);
                                    const tomorrow = new Date(
                                      Date.now() + 24 * 60 * 60 * 1000,
                                    );
                                    setSnoozeUntil(
                                      tomorrow.toISOString().slice(0, 16),
                                    );
                                  }}
                                >
                                  <AlarmClock className="h-4 w-4 text-warning" />
                                  Snooze…
                                </DropdownMenuItem>
                              </>
                            )}
                            {t.status === "RESOLVED" && (
                              <DropdownMenuItem
                                onClick={() => reopen(t.id)}
                                disabled={actionPending}
                              >
                                <RotateCcw className="h-4 w-4" /> Reopen
                              </DropdownMenuItem>
                            )}
                            <DropdownMenuItem onClick={() => setViewing(t)}>
                              <ClipboardList className="h-4 w-4" /> Details
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Resolve dialog */}
      <Dialog
        open={resolving !== null}
        onOpenChange={(v) => !v && setResolving(null)}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Mark task resolved</DialogTitle>
            <DialogDescription>
              {resolving?.title}. Adds a resolution note to the task history.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Label htmlFor="resolutionNote">Resolution note (optional)</Label>
            <Textarea
              id="resolutionNote"
              rows={3}
              value={resolutionNote}
              onChange={(e) => setResolutionNote(e.target.value)}
              placeholder="What was the outcome? E.g. 'Confirmed sender, marked tx as completed.'"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setResolving(null)}>
              Cancel
            </Button>
            <Button
              variant="success"
              onClick={submitResolve}
              disabled={actionPending}
            >
              {actionPending && <Loader2 className="animate-spin" />}
              <Check className="h-4 w-4" /> Resolve
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Snooze dialog */}
      <Dialog
        open={snoozing !== null}
        onOpenChange={(v) => !v && setSnoozing(null)}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Snooze task</DialogTitle>
            <DialogDescription>
              The task drops out of the Open queue until the chosen time, then
              wakes back into Open on the next Auto-detect run.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Label htmlFor="snoozeUntil">Wake at</Label>
            <Input
              id="snoozeUntil"
              type="datetime-local"
              value={snoozeUntil}
              onChange={(e) => setSnoozeUntil(e.target.value)}
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setSnoozing(null)}>
              Cancel
            </Button>
            <Button onClick={submitSnooze} disabled={actionPending}>
              {actionPending && <Loader2 className="animate-spin" />}
              <AlarmClock className="h-4 w-4" /> Snooze
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Details dialog */}
      <Dialog
        open={viewing !== null}
        onOpenChange={(v) => !v && setViewing(null)}
      >
        <DialogContent className="max-w-lg">
          {viewing && (
            <>
              <DialogHeader>
                <DialogTitle>{viewing.title}</DialogTitle>
                <DialogDescription>
                  <Badge variant={CATEGORY_META[viewing.category].variant}>
                    {CATEGORY_META[viewing.category].label}
                  </Badge>
                </DialogDescription>
              </DialogHeader>
              <dl className="grid grid-cols-3 gap-x-3 gap-y-2 text-sm">
                <dt className="text-muted-foreground">Customer</dt>
                <dd className="col-span-2">
                  {viewing.customerEmail ?? "—"}
                  {viewing.customerBlocked && (
                    <span className="ml-2 inline-flex items-center gap-1 rounded bg-destructive/10 px-1.5 py-0.5 text-[10px] font-medium text-destructive">
                      blocked
                    </span>
                  )}
                </dd>
                <dt className="text-muted-foreground">Telegram</dt>
                <dd className="col-span-2">
                  {viewing.customerTelegramId ? (
                    <TelegramHandleLink
                      handle={viewing.customerTelegramId}
                    />
                  ) : (
                    <span className="text-muted-foreground">—</span>
                  )}
                </dd>
                <dt className="text-muted-foreground">Profile</dt>
                <dd className="col-span-2">{viewing.profileName ?? "—"}</dd>
                <dt className="text-muted-foreground">Amount</dt>
                <dd className="col-span-2">
                  {viewing.amountCents != null
                    ? formatUSD(viewing.amountCents)
                    : "—"}
                </dd>
                <dt className="text-muted-foreground">Paid at</dt>
                <dd className="col-span-2">
                  {viewing.paidAt ? formatDateTime(viewing.paidAt) : "—"}
                </dd>
                <dt className="text-muted-foreground">Due at</dt>
                <dd className="col-span-2">
                  {viewing.dueAt ? formatDateTime(viewing.dueAt) : "—"}
                </dd>
                {viewing.snoozedUntil && (
                  <>
                    <dt className="text-muted-foreground">Snoozed until</dt>
                    <dd className="col-span-2">
                      {formatDateTime(viewing.snoozedUntil)}
                    </dd>
                  </>
                )}
                <dt className="text-muted-foreground">Priority</dt>
                <dd className="col-span-2">
                  {PRIORITY_META[viewing.priority].label}
                </dd>
                <dt className="text-muted-foreground">Created</dt>
                <dd className="col-span-2">
                  {formatDateTime(viewing.createdAt)}{" "}
                  {viewing.createdByLabel && (
                    <span className="text-xs text-muted-foreground">
                      · by {viewing.createdByLabel}
                    </span>
                  )}
                </dd>
                {viewing.resolvedAt && (
                  <>
                    <dt className="text-muted-foreground">Resolved</dt>
                    <dd className="col-span-2">
                      {formatDateTime(viewing.resolvedAt)}
                      {viewing.resolvedByLabel && (
                        <span className="text-xs text-muted-foreground">
                          {" "}
                          · by {viewing.resolvedByLabel}
                        </span>
                      )}
                    </dd>
                  </>
                )}
                {viewing.transactionRef && (
                  <>
                    <dt className="text-muted-foreground">Transaction</dt>
                    <dd className="col-span-2">
                      <Link
                        href="/admin/transactions"
                        className="font-mono text-xs text-primary hover:underline"
                      >
                        {viewing.transactionRef}
                      </Link>
                    </dd>
                  </>
                )}
              </dl>
              {viewing.reason && (
                <div className="space-y-1">
                  <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Reason
                  </p>
                  <p className="whitespace-pre-wrap rounded-lg border bg-muted/30 p-3 text-sm">
                    {viewing.reason}
                  </p>
                </div>
              )}
              {viewing.notes && (
                <div className="space-y-1">
                  <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Notes
                  </p>
                  <p className="whitespace-pre-wrap rounded-lg border bg-muted/30 p-3 text-sm">
                    {viewing.notes}
                  </p>
                </div>
              )}
              <DialogFooter>
                <Button variant="outline" onClick={() => setViewing(null)}>
                  Close
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Bulk delete confirm */}
      <Dialog
        open={confirmDelete}
        onOpenChange={(v) => !v && setConfirmDelete(false)}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              Delete {selected.size} task{selected.size === 1 ? "" : "s"}?
            </DialogTitle>
            <DialogDescription>
              This permanently removes{" "}
              {selected.size === 1 ? "this task" : "these tasks"} from the
              follow-up queue. This can&apos;t be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setConfirmDelete(false)}>
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={deleteSelected}
              disabled={deletePending}
            >
              {deletePending && <Loader2 className="animate-spin" />}
              <Trash2 className="h-4 w-4" /> Delete permanently
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

function NewTaskDialog({
  customers,
  profiles,
  transactions,
  onDone,
}: {
  customers: CustomerOption[];
  profiles: ProfileOption[];
  transactions: TransactionOption[];
  onDone: () => void;
}) {
  const [pending, startTransition] = useTransition();
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState<AdminTaskCategory>("PAYMENT_HOLD");
  const [priority, setPriority] = useState<AdminTaskPriority>("NORMAL");
  const [customerId, setCustomerId] = useState<string>("");
  const [profileId, setProfileId] = useState<string>("");
  const [transactionId, setTransactionId] = useState<string>("");
  const [amount, setAmount] = useState("");
  const [paidAt, setPaidAt] = useState("");
  const [dueAt, setDueAt] = useState(() => {
    const d = new Date(Date.now() + 24 * 60 * 60 * 1000);
    return d.toISOString().slice(0, 16);
  });
  const [reason, setReason] = useState("");
  const [notes, setNotes] = useState("");

  // When a transaction is picked, auto-populate the linked customer/profile +
  // money fields so the admin doesn't have to re-enter them.
  const onPickTransaction = (id: string) => {
    setTransactionId(id);
    const tx = transactions.find((t) => t.id === id);
    if (tx) {
      setCustomerId(tx.userId);
      setProfileId(tx.profileId);
      setAmount((tx.amountCents / 100).toFixed(2));
      setPaidAt(new Date(tx.createdAt).toISOString().slice(0, 16));
      if (!title) {
        setTitle(`Payment pending confirmation — ${tx.senderName}`);
      }
    }
  };

  const filteredProfiles = useMemo(
    () =>
      customerId
        ? profiles.filter((p) => p.userId === customerId)
        : profiles,
    [profiles, customerId],
  );

  const submit = () => {
    if (title.trim().length < 3) {
      toast.error("Give the task a short title");
      return;
    }
    const amountCents = amount
      ? Math.round(Number(amount) * 100)
      : undefined;
    if (amount && (!Number.isFinite(amountCents) || amountCents! < 0)) {
      toast.error("Enter a valid amount");
      return;
    }
    let paidAtDate: Date | undefined;
    if (paidAt) {
      const d = new Date(paidAt);
      if (Number.isNaN(d.getTime())) {
        toast.error("Invalid paid date");
        return;
      }
      paidAtDate = d;
    }
    let dueAtDate: Date | undefined;
    if (dueAt) {
      const d = new Date(dueAt);
      if (Number.isNaN(d.getTime())) {
        toast.error("Invalid due date");
        return;
      }
      dueAtDate = d;
    }

    startTransition(async () => {
      const res = await adminCreateTask({
        title: title.trim(),
        category,
        priority,
        customerId: customerId || undefined,
        profileId: profileId || undefined,
        transactionId: transactionId || undefined,
        amountCents,
        paidAt: paidAtDate,
        dueAt: dueAtDate,
        reason: reason.trim() || undefined,
        notes: notes.trim() || undefined,
      });
      if (res.ok) {
        toast.success("Task created.");
        onDone();
      } else {
        toast.error(res.error);
      }
    });
  };

  return (
    <DialogContent className="flex max-h-[90vh] max-w-lg flex-col gap-0 p-0">
      <DialogHeader className="border-b px-6 py-4">
        <DialogTitle>Create a new task</DialogTitle>
        <DialogDescription>
          Use this to remind yourself about a payment you&apos;ve been paid for
          but haven&apos;t processed yet, a restricted account that needs
          attention, or any other admin follow-up.
        </DialogDescription>
      </DialogHeader>

      <div className="flex flex-1 flex-col gap-4 overflow-y-auto px-6 py-5">
        <div className="space-y-2">
          <Label htmlFor="title">Title</Label>
          <Input
            id="title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="What needs doing?"
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <Label>Category</Label>
            <Select
              value={category}
              onValueChange={(v) => setCategory(v as AdminTaskCategory)}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {(Object.keys(CATEGORY_META) as AdminTaskCategory[]).map((k) => (
                  <SelectItem key={k} value={k}>
                    {CATEGORY_META[k].label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Priority</Label>
            <Select
              value={priority}
              onValueChange={(v) => setPriority(v as AdminTaskPriority)}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {(Object.keys(PRIORITY_META) as AdminTaskPriority[]).map((k) => (
                  <SelectItem key={k} value={k}>
                    {PRIORITY_META[k].label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="space-y-2">
          <Label>Linked transaction (optional)</Label>
          <Select value={transactionId} onValueChange={onPickTransaction}>
            <SelectTrigger>
              <SelectValue placeholder="Pick a pending or scheduled transaction" />
            </SelectTrigger>
            <SelectContent className="max-h-72">
              {transactions.length === 0 && (
                <div className="px-3 py-2 text-xs text-muted-foreground">
                  No pending or scheduled transactions
                </div>
              )}
              {transactions.map((t) => (
                <SelectItem key={t.id} value={t.id}>
                  {formatUSD(t.amountCents)} · {t.senderName} ·{" "}
                  <span className="text-muted-foreground">
                    {t.userEmail}
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <p className="text-xs text-muted-foreground">
            Picking one auto-fills the customer, profile and amount below.
          </p>
        </div>

        <div className="space-y-2">
          <Label>Customer</Label>
          <Select
            value={customerId}
            onValueChange={(v) => {
              setCustomerId(v);
              setProfileId("");
            }}
          >
            <SelectTrigger>
              <SelectValue placeholder="Pick a customer (optional)" />
            </SelectTrigger>
            <SelectContent className="max-h-72">
              {customers.map((c) => (
                <SelectItem key={c.id} value={c.id}>
                  {c.email}
                  {c.blocked ? " · blocked" : ""}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label>Profile</Label>
          <Select
            value={profileId}
            onValueChange={setProfileId}
            disabled={filteredProfiles.length === 0}
          >
            <SelectTrigger>
              <SelectValue placeholder="Pick a profile (optional)" />
            </SelectTrigger>
            <SelectContent className="max-h-72">
              {filteredProfiles.map((p) => (
                <SelectItem key={p.id} value={p.id}>
                  {p.label} · {p.status}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <Label htmlFor="amount">Amount paid (USD)</Label>
            <Input
              id="amount"
              type="number"
              inputMode="decimal"
              step="0.01"
              min="0"
              placeholder="0.00"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="paidAt">Paid date</Label>
            <Input
              id="paidAt"
              type="datetime-local"
              value={paidAt}
              onChange={(e) => setPaidAt(e.target.value)}
            />
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="dueAt">Due date</Label>
          <Input
            id="dueAt"
            type="datetime-local"
            value={dueAt}
            onChange={(e) => setDueAt(e.target.value)}
          />
          <p className="text-xs text-muted-foreground">
            Tasks past their due date appear in the <strong>Overdue</strong> tab.
          </p>
        </div>

        <div className="space-y-2">
          <Label htmlFor="reason">
            Reason it hasn&apos;t been processed yet
          </Label>
          <Textarea
            id="reason"
            rows={3}
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder="E.g. awaiting sender verification, ID check pending, bank confirmation, etc."
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="notes">Additional notes (optional)</Label>
          <Textarea
            id="notes"
            rows={2}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Related ticket links, what's been tried, anything else relevant."
          />
        </div>
      </div>

      <DialogFooter className="border-t bg-background px-6 py-4">
        <Button type="button" variant="outline" onClick={onDone}>
          <X /> Cancel
        </Button>
        <Button onClick={submit} disabled={pending}>
          {pending && <Loader2 className="animate-spin" />}
          <CalendarClock className="h-4 w-4" /> Create task
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}
